version: "3"

services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: web-qr
    restart: always
    #platform: linux/arm64/v8
#      - linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # NGINX가 8082로 프록시
    environment:
      - "spring_profiles_active=prod"
