version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # nginx.conf를 mount.
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - web
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot:arm32v6-latest
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: web
    restart: always
    #platform: linux/arm64/v8
#      - linux/amd64
    build:
      # context: .
      #dockerfile: /Users/stella6767/IdeaProjects/free/Dockerfile
      dockerfile: /home/ubuntu/cicd/qr/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - "spring_profiles_active=prod"
