version: "3"

services:
  web:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: web-qr
    restart: always
    #platform: linux/arm64/v8
#      - linux/amd64
    build:
      # context: .
      #dockerfile: /Users/stella6767/IdeaProjects/free/Dockerfile
      dockerfile: /home/ubuntu/cicd/qr/Dockerfile
    ports:
      - "8082:80" # NGINX가 8082로 프록시
    environment:
      - "spring_profiles_active=prod"
