name: Java CI with Gradle DEV

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to use'
        required: true
        default: 'main'
        type: choice
        options:
          - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      
      - uses: actions/checkout@v3
        with:
          #ref: ${{ github.event.inputs.target-branch }}  # 왜 안 먹히냐...
          ref: ${{ inputs.branch }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:         
          java-version: '21'
          distribution: 'temurin'

      -  name: Retrieve secrets
         env:
           MY_SECRETS_ARCHIVE: ${{ secrets.MY_SECRETS_ARCHIVE }}
         run: |
           echo "$MY_SECRETS_ARCHIVE" | base64 --decode > secrets.tar.gz
           tar xzvf secrets.tar.gz -C src/main/resources/     

          
      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicdsample
          retention-days: 1
          path: |
           build/libs/
           scripts/           
           Dockerfile
           docker-compose-qr.yml

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
           name: cicdsample
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: check File List
        run: |
         pwd
         ls -al

      - name: SCP transfer
        run: |
         scp -r scripts build/libs/*.jar Dockerfile docker-compose-qr.yml ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:~/cicd/qr

      - name: Execute remote commands
        run: |
          if [[ "${{ inputs.branch }}" == "main" ]]; then
             ssh -v ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "sudo sh ~/cicd/qr/scripts/deploy-docker.sh"
          else
            echo "No specific script found for this"
          fi
     # delete-artifact
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: cicdsample
